package hr.java.payroll.enums;

/**
 * Represents various job positions within a company.
 *
 * @author Lovro Bilanović
 * @version 1.0
 */
public enum Position {
    CEO, COO, CFO, CTO, DIRECTOR_OF_OPERATIONS, DIRECTOR_OF_MARKETING, DIRECTOR_OF_ENGINEERING,
    PRODUCT_MANAGER, PROJECT_MANAGER, SALES_MANAGER, MARKETING_MANAGER, HUMAN_RESOURCES_MANAGER,
    OPERATIONS_MANAGER, FINANCE_MANAGER, SOFTWARE_ENGINEER, QUALITY_ASSURANCE_ENGINEER, SYSTEMS_ENGINEER,
    DATA_SCIENTIST, IT_SPECIALIST, NETWORK_ENGINEER, ADMINISTRATIVE_ASSISTANT, CUSTOMER_SERVICE_REPRESENTATIVE,
    IT_SUPPORT_SPECIALIST, OFFICE_MANAGER
}
