DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS CONTRACT_FULL_TIME;
DROP TABLE IF EXISTS CONTRACT_PART_TIME;
DROP TABLE IF EXISTS CONTRACT;
DROP TABLE IF EXISTS PAYROLL_HISTORY;

CREATE TABLE CONTRACT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    POSITION VARCHAR NOT NULL,
    BASE_SALARY DECIMAL NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL
);

CREATE TABLE CONTRACT_FULL_TIME (
    ID BIGINT PRIMARY KEY REFERENCES CONTRACT(ID) ON DELETE CASCADE,
    BONUS DECIMAL(7, 2) NOT NULL
);

CREATE TABLE CONTRACT_PART_TIME (
    ID BIGINT PRIMARY KEY REFERENCES CONTRACT(ID) ON DELETE CASCADE,
    HOURS_WORKED DECIMAL NOT NULL,
    HOURLY_RATE DECIMAL NOT NULL
);

CREATE TABLE EMPLOYEE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR NOT NULL,
    LAST_NAME VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL UNIQUE,
    PASSWORD VARCHAR NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    GENDER VARCHAR NOT NULL,
    CONTRACT_ID BIGINT NOT NULL,
    ROLE VARCHAR NOT NULL,
    FOREIGN KEY (CONTRACT_ID) REFERENCES CONTRACT(ID)
);

CREATE TABLE PAYROLL_HISTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_ID BIGINT NOT NULL,
    GROSS_SALARY DECIMAL NOT NULL,
    NET_SALARY DECIMAL NOT NULL,
    BONUS DECIMAL,
    HOURS_WORKED DECIMAL NOT NULL,
    PAYROLL_PERIOD VARCHAR NOT NULL,
    PAYMENT_DATE DATE NOT NULL
);

INSERT INTO CONTRACT (NAME, POSITION, BASE_SALARY, START_DATE, END_DATE) VALUES
('Executive Leadership Contract', 'CEO', 12000.00, '2023-01-01', '2028-01-01'),
('Technology Leadership Contract', 'CTO', 11000.00, '2024-02-01', '2029-02-01'),
('Product Development Agreement', 'PRODUCT_MANAGER', 6800.00, '2023-05-10', '2026-05-10'),
('Sales Strategy Agreement', 'SALES_MANAGER', 7200.00, '2024-01-15', '2027-01-15'),
('IT Support Contract', 'IT_SUPPORT_SPECIALIST', 4500.00, '2023-09-01', '2026-09-01');

INSERT INTO CONTRACT_FULL_TIME (ID, BONUS) VALUES
(1, 3000.00),
(2, 2500.00),
(3, 1500.00);

INSERT INTO CONTRACT_PART_TIME (ID, HOURS_WORKED, HOURLY_RATE) VALUES
(4, 60, 6), 
(5, 70, 6);


INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, DATE_OF_BIRTH, GENDER, CONTRACT_ID, ROLE)
VALUES 
('Marko', 'Horvat', 'marko.horvat@example.com', '$2a$12$dWmWpZce16uzxPHst1lEyuBpL15YI7.KgTNMGFTM/bUlgwcxyEprO', '1990-05-15', 'MALE', 1, 'USER'), -- password Marko123€
('Ana', 'Ivić', 'ana.ivic@example.com', '$2a$12$YCVUtnqv04BIIDphFuqp/O54WlP0KoiL3RU5r7WtGnukCvC49etd2', '1985-09-23', 'FEMALE', 2, 'USER'), -- password Ana123€
('Petar', 'Kovačić', 'petar.kovacic@example.com', '$2a$12$L2oo1aeHfw7OLzlr23cvsu4CaYhWS7NJt60pDP5oNKl6aqOcIpEGG', '1993-02-02', 'MALE', 3, 'USER'), -- password Petar123€
('Ivana', 'Jurić', 'ivana.juric@example.com', '$2a$12$zFWMo.th7PVgOKboP4AsKuWuQF21lll6rrFKIG8qGbYZzXQ/3KE.i', '1998-12-17', 'FEMALE', 4, 'USER'); -- password Ivana123€



